### ISSUE TITLE
Discover Inbox through Link rel Header 

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#156]

**Comment by csarven** [comment]
At the moment, dokieli doesn't create resources where the server can send a Link header with the inbox URL. The only way that can work is a server supporting that feature serves a dokieli article.

**Comment by rhiaro** [comment]
That's fine, my server serves dokieli articles with link header.. Very
convenient for people who aren't using solid/LDP to host articles,
especially since dokieli doesn't have a way to insert inbox in body other
than handwriting html currently.

Also can check link header when sharing with a person selected from
contacts?

**Comment by csarven** [comment]
It is whenever `getInbox` is called. If URL parameter is provided it will check HEAD of that, then try GET/body. Otherwise, it parses the current document for the inbox, if not found, it will try HEAD. I can refactor this to always check HEAD first.. but parsing the current document on hand is not a new fetch.
