### ISSUE TITLE
Unable to make new paragraphs in Firefox

### ISSUE THREAD

**Issue by adamemerson** [dokieli/dokieli#250]
I hit enter at the end of a paragraph, but it won't let me type any text into it. If I backspace back into the previous paragraph I can continue typing.

**Comment by csarven** [comment]
Can you tell which stylesheet is was applied? You can see this from the dokieli menu.

If the document that you're trying is public, what's the URL?

**Comment by adamemerson** [comment]
All right, I think I might have described this wrong, since I tried making a sample document to show the problem. The behavior I'm actually seeing is:

I can create a document. I can type a paragraph. If I try to make another paragraph I can't type in the new paragraph.

HOWEVER, if I then hit 'save'. Once I hit save I can make additional paragraphs.

Unfortunately it tells me that the server does not allow this resource to be rewritten.

So while I can type in text and create paragraphs, I can't save anything to the document and the permanent form stays blank. (This is using the 'Basic' stylesheet.)

https://azure.inrupt.net/public/Test/

**Comment by csarven** [comment]
Ah, I see. Thanks for reporting.

I think what's happening is due to inrupt.net requiring WebID-OIDC based authentication and at the moment, dokieli is not using that (only relying on WebID-TLS). WebID-OIDC will be supported soon.

In the meantime, just to quickly iron out this issue, can you try to change the access controls to that resource so that it is public write? I suggest using a resource like https://azure.inrupt.net/public/Test/foo instead of / to test. If you're able save and everything looks fine after refreshing the URL, we can close this issue if you agree.
