### ISSUE TITLE
dokieli Basic use

### ISSUE THREAD

**Issue by scenaristeur** [dokieli/dokieli#269]
I can't use Dokieli, 
any idea ? 
https://forum.solidproject.org/t/coders-non-coders/823/5?u=smag0

![](https://forum.solidproject.org/uploads/default/original/1X/f875c88ae2bc3a228d56562fef7efe82062f1d89.png)

**Comment by csarven** [comment]
Thanks for reporting. That doesn't look like an issue with with dokieli. If the server that's running off is using node-solid-server 4.x, it is highly likely the reason of that issue. You may want to rename the resource to include `.html` (so start.html) and try again on that particular server. node-solid-server v5 will have that resolved in that, it should (in theory) show you 'start' without the explicit .html suffix.

For future issues, can you please post the full content of an issue in here, so that we can better understand the underlying issue and document. Otherwise, it is makes hard to debug.

If this response is satisfactory, I suggest closing. Would you like to?

**Comment by scenaristeur** [comment]
This happened on the solid.community server. I don't know in what version it is .
Ok to close
