### ISSUE TITLE
On SaveAs don't open new window until document actually created

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#81]
If creating the new document fails (most likely due to not authenticating with the URL input) then the new window/tab opens over the top and just stays blank. Even when #50 is done, the user won't see the error without clicking back to the original document, so a new window/tab should only be opened on success.

**Comment by rhiaro** [comment]
Also if you're not authenticated, the blank window opens over the top, hiding the cert popup to allow you to authenticate, so unless you know to click back to choose a cert it seems like nothing is happening.

**Comment by csarven** [comment]
I agree. Had two `FIXME`s lines in code about this. Marking this as a bug b/c the UX around the window opening is _bleh_ such that it needs attention.

**Comment by csarven** [comment]
I just realized that what was initially done was due to trying to get it to open up in a new _tab_ as opposed to a new window. This is in the end the browser's decision (based on user's settings), but IIRC, Firefox was not letting me open a new tab in one of the cases (and that's the default for me) and somehow turned it into a window. One other case was where it just wouldn't open at all. I don't have further details as I'm only recalling at the moment.

**Comment by rhiaro** [comment]
Sometimes Chrome is pop-up blocking the new window for me.

Should probably also have a clickable URL to the new document in the original document UI, as a backup for when the user's browser does stuff like this.

**Comment by csarven** [comment]
+1 to having a clickable URL. The current process however closes the new/save as input containers once it is successful. Might have to rethink the UI for that.. (quickly: perhaps for #85 to resolve).

**Comment by rhiaro** [comment]
Okay, did [that](https://github.com/linkeddata/dokieli/issues/81#issuecomment-170274532) in [a89f8](https://github.com/rhiaro/dokieli/commit/a89f87a93e9bd0880e2cc2e039f303a67ae1a0a4)
