### ISSUE TITLE
UI for notifications inbox link

### ISSUE THREAD

**Issue by rhiaro** [dokieli/dokieli#94]
Find a nice way to display the notifications inbox that will look good for most types of article, or have some options the user can set (eg. I could see wanting to hide the link altogether in Read mode, and it only actually needs to be in there machine-readably anyway)

**Comment by csarven** [comment]
Currently, we pile up brief definition-list like stuff (or metadata, depending on how you look at it) near the header region - above the main content of the document. I think we should stick to that for now - keep it visible. When the UI is a bit more advanced, it'll should be possible to move it around in the document e.g., to the footer, or hide completely from view. This whole thing depends on another dokieli feature which is not yet defined.

**Comment by rhiaro** [comment]
We also need UI for _adding_ an inbox link to a document, and creating the inbox if it doesn't already exist.

**Comment by csarven** [comment]
There is https://github.com/linkeddata/dokieli/issues/110 which is intended to cover the feature on adding an inbox to the article.

**Comment by csarven** [comment]
https://github.com/linkeddata/dokieli/issues/396 covers user inputting the inbox URL. What remains of this issue is perhaps the UI part where while an inbox may be associated with the article, the user should have the option to hide the inbox text/URL as a whole. To that end, that will be follow up / considered as part of https://github.com/linkeddata/dokieli/issues/401 .
